### ISSUE TITLE
條目中出現「未來時間」

### ISSUE THREAD

**Issue by jbytw** [g0v/twangry#123]
2015.07.29 時出現 2015.10.27 的條目。大概是前後文判斷失準，wiki 上應為 2008。

http://fact.g0v.tw/wikipedia/%E8%87%BA%E7%81%A3%E9%AB%98%E4%B8%AD%E6%AD%B7%E5%8F%B2%E8%AA%B2%E7%B6%B1%E5%BE%AE%E8%AA%BF%E6%A1%88#72
![image](https://cloud.githubusercontent.com/assets/5170081/8947864/f88edb4e-35d2-11e5-879b-4c897dbfce81.png)

**Comment by jimyhuang** [comment]
感謝回報。
該時間因為取「引用文章」中的時間，導致出錯。理當用前文脈絡提到的年份。

不過目前邏輯無法判斷是否引用文章時間出錯...
所以建議的邏輯為何？是否還是直接用前文時間？

**Comment by jbytw** [comment]
「引用文章」指的是該篇新聞？如果 wiki 前文脈絡中有年份的話，一般來說應該正確？
我的觀察啦。

當初選用「引用文章」的時間原因是？

**Comment by jimyhuang** [comment]
當初發現前文脈絡的年份，有時會抓錯，所以會抓引用文章做比對...結果沒想到引用來源的年份也有錯

經你一提，可能有兩個方案：

a. 簡易版：前文脈絡年份有，就直接套用
b. 嚴格版：前文脈絡年份有，若該段落有引用外部來源，double confirm 外步來源的年份，如果相同才指定年份

看有沒有任何建議

**Comment by jbytw** [comment]
問：
b. 如果[前文]和[外部來源]年份不同 --> 是人工介入還是取用哪個？

**Comment by jimyhuang** [comment]
> 如果[前文]和[外部來源]年份不同 

那只好直接棄用該段落了 XD

**Comment by jbytw** [comment]
(也對，我想過頭了XD)
